-- @a7mdh4am
CREATE TABLE AuditLog (
    LogID INT PRIMARY KEY AUTO_INCREMENT,
    TableName NVARCHAR (100) NOT NULL,
    Operation NVARCHAR (10) NOT NULL,
    RecordID INT NOT NULL,
    ChangedBy NVARCHAR (100) NOT NULL,
    ChangedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)