-- @a7mdh4am
CREATE TABLE AuditLog (
    LogID SERIAL PRIMARY KEY,
    TableName VARCHAR (100) NOT NULL,
    Operation VARCHAR (10) NOT NULL,
    RecordID INT NOT NULL,
    ChangedBy VARCHAR (100) NOT NULL,
    ChangedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)